service: wof-tracking-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2023
  deploymentBucket:
    name: rtrydev-serverless-deployments-${opt:region}
  httpApi:
    cors:
      allowedOrigins: '*'
      allowedHeaders:
        - Content-Type
        - X-Amz-Date
        - Authorization
        - X-Api-Key
        - X-Amz-Security-Token
        - X-Amz-User-Agent
    authorizers:
      wofAuthorizer:
        type: request
        functionArn: 'arn:aws:lambda:${aws:region}:${aws:accountId}:function:wof-authorizer-dev-authorize'

package:
  individually: true
  exclude:
    - '**/*'

functions:
  trackEvent:
    handler: src/ports/lambda/main.go
    package:
      include:
        - 'src/**/*.go'
    events:
      - httpApi:
          path: /
          method: post
          authorizer: wofAuthorizer
  getTracking:
    handler: src/ports/lambda/main.go
    package:
      include:
        - 'src/**/*.go'
    events:
      - httpApi:
          path: /{schema_id}
          method: post
          authorizer: wofAuthorizer

custom:
  go:
    supportedRuntimes: ['provided.al2023']
    buildProvidedRuntimeAsBootstrap: true

plugins:
  - serverless-deployment-bucket
  - serverless-go-plugin
